# Generated by Django 4.2 on 2023-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hobby_user_bio_user_gender_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_income',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='annual_income'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='occupation'),
        ),
    ]
