# Generated by Django 4.2 on 2023-04-18 07:30

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_annual_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.ProfileImage.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Profile Images',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, choices=[(2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950)], null=True)),
                ('birth_month', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('birth_day', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True)),
                ('gender', models.CharField(blank=True, choices=[('未登録', '未登録'), ('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('未登録', '未登録'), ('IT業界', 'IT業界'), ('医療業界', '医療業界'), ('教育業界', '教育業界'), ('製造業', '製造業'), ('小売業', '小売業'), ('公務員', '公務員'), ('金融業界', '金融業界'), ('法律業界', '法律業界'), ('美容業界', '美容業界'), ('飲食業界', '飲食業界'), ('不動産業界', '不動産業界'), ('芸能・エンターテインメント業界', '芸能・エンターテインメント業界'), ('スポーツ選手', 'スポーツ選手'), ('その他', 'その他')], max_length=50, null=True)),
                ('annual_income', models.CharField(blank=True, choices=[('未登録', '未登録'), ('300万未満', '300万未満'), ('300-400万', '300-400万'), ('400-500万', '400-500万'), ('500-600万', '500-600万'), ('600-700万', '600-700万'), ('700-800万', '700-800万'), ('800-900万', '800-900万'), ('900-1000万', '900-1000万'), ('1000万以上', '1000万以上')], max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.UserProfile.user_directory_path)),
                ('goals', models.ManyToManyField(blank=True, to='accounts.goal')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='accounts.hobby'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_areas',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.area'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
