# Generated by Django 4.2 on 2023-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_area_goal_profileimage_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='upload_source',
            field=models.CharField(blank=True, choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('form5', 'Form 5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_areas',
            field=models.ManyToManyField(blank=True, to='accounts.area'),
        ),
    ]
