# Generated by Django 4.2 on 2023-04-19 08:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profileimage_upload_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profile_image1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image2',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UserProfile.user_directory_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image3',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UserProfile.user_directory_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image4',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UserProfile.user_directory_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image5',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UserProfile.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='annual_income',
            field=models.CharField(blank=True, choices=[('未登録', '未登録'), ('300万未満', '300万未満'), ('300-400万', '300-400万'), ('400-500万', '400-500万'), ('500-600万', '500-600万'), ('600-700万', '600-700万'), ('700-800万', '700-800万'), ('800-900万', '800-900万'), ('900-1000万', '900-1000万'), ('1000万以上', '1000万以上')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('未登録', '未登録'), ('IT業界', 'IT業界'), ('医療業界', '医療業界'), ('教育業界', '教育業界'), ('製造業', '製造業'), ('小売業', '小売業'), ('公務員', '公務員'), ('金融業界', '金融業界'), ('法律業界', '法律業界'), ('美容業界', '美容業界'), ('飲食業界', '飲食業界'), ('不動産業界', '不動産業界'), ('芸能・エンターテインメント業界', '芸能・エンターテインメント業界'), ('スポーツ選手', 'スポーツ選手'), ('その他', 'その他')], max_length=30, null=True),
        ),
    ]
